### ISSUE TITLE
[Mob] Crust Bursters and similar type mobs

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#11]
Crust Bursters required as quest kills do not correctly initiate combat. They pop in and out of the ground and quickly go in and out of combat. Occasionally, they will appear to stick out of the ground for extended periods of time but are not animated and slowly move in one direction. They are pretty heavily bugged. Their larger counterparts work just fine, however, rare elites and other very large crust burster type mobs are not glitched.

**Comment by Chuck5ta** [comment]
Fix has now been applied to One and Two:

https://github.com/mangosone/database/pull/22
https://github.com/mangostwo/database/pull/35

**Comment by billy1arm** [comment]
@tbayart - thanks again, thanks for that sorry it took so long to get it processed
