### ISSUE TITLE
[Quest] Death's Door (#10910)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#13]
The quest Death's Door is automatically completed upon accepting it. Furthermore, the 20 or so Evergrove Druids that float hidden above the Death's Door zone are not given NPC models, are not targetable, and do not react to the use of the quest item "Druid Signal" (#31763). They have a display id of #11686 but no actual model is visible. This quest and subsequent quests are not completable.

**Comment by Necrovoice** [comment]
logged
