### ISSUE TITLE
[Quest] Maggoc's Treasure Chest (#10996)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#22]
Similar problem as Grulloc, Maggoc's Treasure Chest (Object #185569) does not appear when he dies. There is an effect that shows a little aura and the quest glitter, shown in the screen shot, but the quest object is not present to loot.

Also the damage for Grulloc, Maggoc, and the other Gronn mobs seem very underpowered and don't hit for very much damage.

![wowscrnshot_010314_232426](https://f.cloud.github.com/assets/3746854/1844199/2f5f29a8-7509-11e3-88d0-d02620fd4f11.jpg)

**Comment by Necrovoice** [comment]
Fixed at some point
