### ISSUE TITLE
[Quest] Into the Soulgrinder (#11000)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#24]
This quest needs a lot of work.

The object, Skulloc's Soul (#185577), is already spawned in front of the Soulgrinder Altar, requiring no effort to complete the quest. Skulloc Soulgrinder (#22910) is not spawned in any form at all, he should be phased and unhostile until the actual in-game event is over with. There is no book near the Altar to begin the original event (I could not find the object ID for this book to test whether an event would even begin).

Temporary workaround:  Removed the Skulloc's Soul object and spawned Skulloc in the purple light. So players must kill him in order to get his soul (which he also drops, and is not exclusive to the Soul object appearing after his death) despite the lack of an event leading up to fighting him.

Furthermore, completing this quest does not make any ogres in the area neutral with you, there is no creature speak regarding you becoming King of the Ogres, and Mog'dorg the Wizened (#22941) does not provide the follow up quest to send you to Ogri'la called Ogre Heaven (#11009).

**Comment by Necrovoice** [comment]
logged
