### ISSUE TITLE
[Quest] Sabotage the Warp-Gate (#10310)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#26]
The escort quest NPC, Drijya (#20281) does not move or begin any scripted event at all.

**Comment by Necrovoice** [comment]
Dup of https://github.com/mangostwo/server/issues/62
Fix on line 83

https://github.com/mangostwo/database/blob/Develop21/World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_02_21_verious_quest_and_gameobjects_update.sql
