### ISSUE TITLE
[Quest] Dimensius the All-Devouring (#10439)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#36]
Captain Saeed (#20985) does not continue the quest to move up to killing Dimensius (#19554). Furthermore, Dimensius is non targetable.

![wowscrnshot_010514_024443](https://f.cloud.github.com/assets/3746854/1846352/0c3cbeb4-75ee-11e3-8848-d024ebd2772b.jpg)

**Comment by Necrovoice** [comment]
Logged
