### ISSUE TITLE
[Quest] The Thane of Voldrune (#12255)

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#57]
Interfacing with the dragon, Flamebringer (#27292), prompts the player with a dialogue "Unchain and control Flamebringer." but selecting this does not initiate any scripted event or allow you to ride the dragon in order to reach Thane Torvald Eriksson

**Comment by Necrovoice** [comment]
Logged here:
https://www.getmangos.eu/bug-tracker/mangos-two/The-Thane-of-Voldrune-(%2312255)-r18/
