### ISSUE TITLE
Blood Draining not work on health < 35%

### ISSUE THREAD

**Issue by arliweng** [mangostwo/server#59]
for now, the enchant "Blood Draining" not work when
GetHealth() < uint32(GetMaxHealth() \* 0.35)

about:
https://github.com/mangostwo/server/commit/eb61995f7e40c1d1da2ba093f011a96d2fc87d57

if (GetHealth() - damage > health35 || GetHealth() < health35)
  return SPELL_AURA_PROC_FAILED;

fix to:

if (GetHealth() - damage > health35)
 return SPELL_AURA_PROC_FAILED;

**Comment by Necrovoice** [comment]
Has been implemented.
