### ISSUE TITLE
Elite creatures never loot

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#60]
When an Elite mob is killed, it never drop anything else than money.

Don't know if there is something broken in database, server ou mangos.conf file.
Maybe something missing.

**Comment by Necrovoice** [comment]
Not enough information (2years old) Unable to reproduce.

**Comment by tbayart** [comment]
It's been a while I didn't run my server. Need to upgrade to latest and try again.
In case this defect still there, what could I do to help you investigate ?

**Comment by billy1arm** [comment]
@tbayart @Necrovoice - If you could, download the develop21 branch and build the server. I think the issue was fixed, but i'm not 100% sure.

iirc - this affected ALL Elite mobs ?

**Comment by billy1arm** [comment]
@tbayart - The develop21 branch is now merged into master

**Comment by billy1arm** [comment]
@Necrovoice - Did we ever get to the bottom of this ?

**Comment by Necrovoice** [comment]
This can be closed
