### ISSUE TITLE
[DB] Quest 10309 fix

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#61]
During the quest, some 'Zaxxis Ambusher' attack the player.
They appear to be green and are unattackable.
I applied this to fix the problem :
update creature_template set faction_A = 16, faction_H = 16 where entry = 20287;

**Comment by billy1arm** [comment]
@tbayart - thanks for this and apologies for it taking to long to get implemented

it's been added in https://github.com/mangostwo/database/commit/8daac055f85e7b1b67f4de92df1248854a1500ad

**Comment by tbayart** [comment]
no problem for the delay
thank you for adding this fix
and glad to be helpful
