### ISSUE TITLE
[DB] Quest 10310

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#62]
The quest needs you to protect an NPC from 3 kind of creatures wich will spawn and attack the npc.
All creatures appears to be green and are unattackable.
I applied those to fix the problem :
update creature_template set faction_A = 90, faction_H = 90 where entry = 20399;
update creature_template set faction_A = 90, faction_H = 90 where entry = 20402;
update creature_template set faction_A = 90, faction_H = 90 where entry = 20403;

**Comment by Necrovoice** [comment]
Fix on line 83

https://github.com/mangostwo/database/blob/Develop21/World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_02_21_verious_quest_and_gameobjects_update.sql

**Comment by Necrovoice** [comment]
@billy1arm 
Just checked.. seems to be and seems to work
