### ISSUE TITLE
[DB] Can't learn first aid from NPC 18990

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#63]
As an alliance player, you can speak to NPC 18990 named 'Burko'.
You should be able to learn first aid from him but to do so, I had to fix his template with this :
UPDATE `mangos`.`creature_template` SET `npcflag`='80' WHERE `entry`='18990';

I didn't test it but I think horde player have the same problem with NPC 18991 named 'Aresella' (same wrong npcflag).
Apply this to fix Aresella :
UPDATE `mangos`.`creature_template` SET `npcflag`='80' WHERE `entry`='18991';

**Comment by Necrovoice** [comment]
Fixed
https://github.com/mangostwo/database/blob/Develop21/World/Updates/Rel21/Rel20_to_BaseRel21_Updates/Rel21_02_19_Outland_first_aid.sql #
