### ISSUE TITLE
Cannon Mob don't stay in place

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#65]
I encountered some "cannon" mobs, like Legion Fel Cannon : http://www.wowhead.com/npc=21233
When the mob start attacking you, it moves to fight in close combat.

I tried to "set unit_flags = 4" bug this don't seems to work.
flag 4 is documented as UNIT_FLAG_DISABLE_MOVE

**Comment by Necrovoice** [comment]
Report made: 
https://www.getmangos.eu/bug-tracker/mangos-two/cannon-mob-dont-stay-in-place-r1319/
