### ISSUE TITLE
Broken Quest Line

### ISSUE THREAD

**Issue by ghost** [mangostwo/server#9]
The quest line starting with Picking Up Some Power Converters (#10584) is non functioning. The quest items either appear to try to work or do not work whatsoever.

For instance, the quest item, Multi-Spectrum Light Trap (#30852) used for the quest Trapping the Light Fantastic (#10674) does not work at all. No trap object is actually placed upon the ground.

In the quest Show Them Gnome Mercy! (#10675), the quest item that should appear over the corpse of Nexus Prince Razaan does not appear.

**Comment by Necrovoice** [comment]
Logged here
https://www.getmangos.eu/bug-tracker/mangos-two/Broken-Quest-Line-r68/
